// Auto-generated by scripts/fetch-jwks.sh — do not edit manually
// Run the script again to rotate the key
import type { JWK } from "jose";

export const PUBLIC_JWK: JWK = {
  kty: "RSA",
  n: "3XdsxI2AqQYDc81C-ieV5RqCPohyuG4Mg5EiggIXCLrJA0t8iYOFcLbF-NfG-7ioWFjAuM_GOn4r5myYbwPoP6tskQ6LBCjLlNaUn9BRsqjplLF7U1FY4aPe28gPfu4xuJDncVQE5UtuRfCDYYmVgWS3CHJf5_jEwNUxlb-OezS6ZYCDvhoxUuooJkxEOnmywqU5DgvkBjAn65vwIu7EDPfFk-7q43X5pd5lbRNfnfJx_4hzdMI-wPv1wUTI5A3hK4Ah6fXcLZKzG-DDLlGVYl6fT7IiE7Sksu_4RZkGEhauFmulKHM_niiog1Z377Kv1VhjmiSfNGKdFjj5lVIWWQ",
  e: "AQAB",
  use: "sig",
  alg: "RS256",
};
