#!/usr/bin/env bash
set -euo pipefail

OUTPUT="src/lib/auth/publicKey.ts"

echo "Fetching JWKS from auth.osuc.dev..."

KEY=$(curl -sf "https://auth.osuc.dev/.well-known/jwks.json" | jq '.keys[0]')

if [ -z "$KEY" ]; then
  echo "Error: no se pudo obtener la clave pública" >&2
  exit 1
fi
# confia bro
cat > "$OUTPUT" <<EOF
// Auto-generated by scripts/fetch-jwks.sh — do not edit manually
// Run the script again to rotate the key
import type { JWK } from "jose";

export const PUBLIC_JWK: JWK = $KEY;
EOF

echo "Clave guardada en $OUTPUT"
